### ISSUE TITLE
Python crashed with Daemon

### ISSUE THREAD

**Issue by Creative-comfyUI** [Jonseed/ComfyUI-Detail-Daemon#9]
Here is the error 

*** First throw call stack:
(
	0   CoreFoundation                      0x000000018d16f2ec __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x000000018cc56788 objc_exception_throw + 60
	2   CoreFoundation                      0x000000018d194268 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x0000000190969348 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 188
	4   AppKit                              0x0000000190969280 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 48
	5   _macosx.cpython-312-darwin.so       0x00000003273e855c -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 52
	6   _macosx.cpython-312-darwin.so       0x00000003273eb540 FigureManager_init + 228
	7   python3.12                          0x0000000104eb7618 wrap_init + 20
	8   python3.12                          0x0000000104e2b5b0 wrapperdescr_call + 700
	9   python3.12                          0x0000000104f76304 _PyEval_EvalFrameDefault + 187584
	10  python3.12                          0x0000000104eb6fd0 slot_tp_init + 328
	11  python3.12                          0x0000000104eab034 type_call + 148
	12  python3.12                          0x0000000104f76304 _PyEval_EvalFrameDefault + 187584
	13  python3.12                          0x0000000104e20bfc method_vectorcall + 304
	14  python3.12                          0x0000000104f7a6bc _PyEval_EvalFrameDefault + 204920
	15  python3.12                          0x0000000104e20bfc method_vectorcall + 304
	16  python3.12                          0x0000000104f7a6bc _PyEval_EvalFrameDefault + 204920
	17  python3.12                          0x0000000104e20c3c method_vectorcall + 368
	18  python3.12                          0x000000010508382c thread_run + 132
	19  python3.12                          0x0000000105001b08 pythread_wrapper + 48
	20  libsystem_pthread.dylib             0x000000018d01af94 _pthread_start + 136
	21  libsystem_pthread.dylib             0x000000018d015d34 thread_start + 8
)
libc++abi: terminating due to uncaught exception of type NSException
zsh: abort      python3 main.py

**Comment by Jonseed** [comment]
I haven't seen that error before (or anything like it), but I think it is unlikely to be related to Detail Daemon. Why do you think it is caused by Detail Daemon?

**Comment by Creative-comfyUI** [comment]
The problem comes from the "Daemon graph sigma" node. When I delete this node the application doesn't crash. It seems that there is something incompatible with this node and python. It is not a memory problem in my opinion. It is the first time that python crash this way.  I am on a Mac. This may explain the problem.
